#!/bin/sh
# Exuno guard — a Claude Code PreToolUse hook.
#
# Agent instructions are generated from .ai/src/, so an edit to a generated
# file is lost on the next sync. This blocks the write and names the source to
# edit instead. Exit 2 is what Claude Code treats as "block and tell the
# agent why"; every other outcome exits 0 so no other tool call is affected.
#
# Generated by Exuno. To change it, put your own copy at
# .ai/src/tools/claude/guard.sh and run: exuno sync

set -u

payload=$(cat)

# tool_input.file_path, without a JSON parser: take the first match and strip
# the escaping Claude Code applies to a path.
file_path=$(printf '%s' "$payload" \
    | tr ',{}' '\n' \
    | grep -m1 '"file_path"' \
    | sed -e 's/.*"file_path"[[:space:]]*:[[:space:]]*"//' -e 's/".*$//' -e 's|\\\\|\\|g')
[ -n "$file_path" ] || exit 0

project_dir="${CLAUDE_PROJECT_DIR:-$PWD}"
manifest="$project_dir/.ai/.sync-manifest"
[ -f "$manifest" ] || exit 0

# Compare repo-relative, so an absolute tool path and a relative manifest
# entry still match.
rel=${file_path#"$project_dir"/}
case "$rel" in
    /*) exit 0 ;;
esac

source_hint=$(awk -F'\t' -v want="$rel" '$1 == want { print "found"; exit }' "$manifest")
[ -n "$source_hint" ] || exit 0

cat >&2 <<EOF
$rel is generated by Exuno and will be overwritten by the next sync.

Edit the matching source under .ai/src/ instead, then run: exuno sync
  - agent identity → .ai/src/AGENTS.md
  - rules          → .ai/src/rules/
  - skills         → .ai/src/skills/
  - commands       → .ai/src/commands/
  - subagents      → .ai/src/agents/
  - settings, MCP  → .ai/src/tools/<tool>/

To keep an edit already made in the generated file: exuno adopt $rel
EOF
exit 2
