//! `tests/guard.bats`: the generated Claude guard, a PreToolUse hook that
//! blocks an edit to a generated file and names the source to edit instead.
//! The guard is a POSIX shell script `agentsync` writes and spawns as `sh`
//! itself — every case here runs that real script, so the whole file is
//! `#[cfg(unix)]`: there is no `sh` to spawn on a bare Windows CI runner.
#![cfg(unix)]

mod common;

use std::path::Path;
use std::process::{Command as StdCommand, Output, Stdio};

use common::Project;

const GUARD: &str = ".claude/hooks/agentsync-guard.sh";

fn synced_project() -> Project {
    Project::seeded(&["--tools", "claude", "--yes"])
}

/// Feed the hook a PreToolUse payload for `path`, as Claude Code would.
fn guard_for(project: &Project, path: &str) -> Output {
    let payload = format!(
        "{{\"hook_event_name\":\"PreToolUse\",\"tool_name\":\"Edit\",\"tool_input\":{{\"file_path\":\"{path}\"}}}}"
    );
    run_guard(project, payload.as_bytes())
}

fn run_guard(project: &Project, stdin: &[u8]) -> Output {
    use std::io::Write;
    let mut child = StdCommand::new("sh")
        .arg(project.join(GUARD))
        .env("CLAUDE_PROJECT_DIR", project.path())
        .current_dir(project.path())
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .unwrap();
    // A hook is free to exit without reading its payload, which closes the
    // pipe under the write: a project override that is just `exit 0` loses
    // this race on a loaded runner.
    match child.stdin.take().unwrap().write_all(stdin) {
        Ok(()) => {}
        Err(e) if e.kind() == std::io::ErrorKind::BrokenPipe => {}
        Err(e) => panic!("writing the hook payload: {e}"),
    }
    child.wait_with_output().unwrap()
}

/// git check-ignore exits 1 for a path that is not ignored — a plain
/// `Project::git` call would treat that as failure, so run it directly.
fn is_git_ignored(project: &Project, rel: &str) -> bool {
    let absent = std::env::temp_dir().join("agentsync-tests-absent-gitconfig");
    StdCommand::new("git")
        .args(["check-ignore", "-q", rel])
        .current_dir(project.path())
        .env("GIT_CONFIG_GLOBAL", &absent)
        .env("GIT_CONFIG_SYSTEM", &absent)
        .status()
        .unwrap()
        .success()
}

fn path_str(path: &Path) -> String {
    path.to_str().unwrap().to_string()
}

#[test]
fn guard_sync_installs_it_as_an_executable_hook() {
    let project = synced_project();
    let path = project.join(GUARD);
    assert!(path.is_file());
    use std::os::unix::fs::PermissionsExt;
    let mode = std::fs::metadata(&path).unwrap().permissions().mode();
    assert!(mode & 0o111 != 0);
}

#[test]
fn guard_settings_point_pretooluse_at_it() {
    let project = synced_project();
    let settings = project.read(".claude/settings.json");
    assert!(settings.contains("agentsync-guard.sh"));
    assert!(settings.contains("PreToolUse"));
}

#[test]
fn guard_it_is_tracked_in_the_manifest_like_any_other_output() {
    let project = synced_project();
    let manifest = project.read(".ai/.sync-manifest");
    assert!(
        manifest
            .lines()
            .any(|line| line.starts_with(&format!("{GUARD}\t")))
    );
}

#[test]
fn guard_blocks_an_edit_to_a_generated_rule_with_exit_2() {
    let project = synced_project();
    let path = path_str(&project.join(".claude/rules/core.md"));
    let output = guard_for(&project, &path);
    assert_eq!(output.status.code(), Some(2));
    let combined = String::from_utf8_lossy(&output.stderr);
    assert!(combined.contains(".ai/src/"));
    assert!(combined.contains("agentsync sync"));
}

#[test]
fn guard_blocks_an_edit_to_the_generated_agents_file() {
    let project = synced_project();
    let path = path_str(&project.join("CLAUDE.md"));
    let output = guard_for(&project, &path);
    assert_eq!(output.status.code(), Some(2));
    assert!(String::from_utf8_lossy(&output.stderr).contains("generated by AgentSync"));
}

#[test]
fn guard_names_adopt_so_an_edit_already_made_can_be_kept() {
    let project = synced_project();
    let path = path_str(&project.join("CLAUDE.md"));
    let output = guard_for(&project, &path);
    assert!(String::from_utf8_lossy(&output.stderr).contains("agentsync adopt CLAUDE.md"));
}

#[test]
fn guard_accepts_a_repo_relative_path_too() {
    let project = synced_project();
    let output = guard_for(&project, "CLAUDE.md");
    assert_eq!(output.status.code(), Some(2));
}

#[test]
fn guard_allows_a_source_file_under_ai_src() {
    let project = synced_project();
    let path = path_str(&project.join(".ai/src/rules/core.md"));
    let output = guard_for(&project, &path);
    assert_eq!(output.status.code(), Some(0));
    assert!(output.stdout.is_empty() && output.stderr.is_empty());
}

#[test]
fn guard_allows_ordinary_project_files() {
    let project = synced_project();
    let path = path_str(&project.join("lib/main.dart"));
    let output = guard_for(&project, &path);
    assert_eq!(output.status.code(), Some(0));
}

#[test]
fn guard_allows_a_file_outside_the_project() {
    let project = synced_project();
    let output = guard_for(&project, "/etc/hosts");
    assert_eq!(output.status.code(), Some(0));
}

#[test]
fn guard_allows_everything_when_there_is_no_manifest() {
    let project = synced_project();
    std::fs::remove_file(project.join(".ai/.sync-manifest")).unwrap();
    let path = path_str(&project.join("CLAUDE.md"));
    let output = guard_for(&project, &path);
    assert_eq!(output.status.code(), Some(0));
}

#[test]
fn guard_allows_a_payload_with_no_file_path() {
    let project = synced_project();
    let payload = br#"{"tool_name":"Bash","tool_input":{"command":"ls"}}"#;
    let output = run_guard(&project, payload);
    assert_eq!(output.status.code(), Some(0));
}

#[test]
fn guard_doctor_warns_when_a_settings_override_never_registers_the_hook() {
    let project = synced_project();
    project.write(
        ".ai/src/tools/claude/settings.json",
        "{\n  \"permissions\": {\n    \"allow\": [\"Read\"]\n  }\n}\n",
    );
    project.exuno().args(["sync", "--force"]).assert().success();
    let output = project.exuno().arg("doctor").output().unwrap();
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(stdout.contains("inert"));
    assert!(stdout.contains("agentsync-guard.sh"));
}

#[test]
fn guard_doctor_stays_quiet_when_the_hook_is_registered() {
    let project = synced_project();
    let output = project.exuno().arg("doctor").output().unwrap();
    assert!(!String::from_utf8_lossy(&output.stdout).contains("inert"));
}

#[test]
fn guard_a_config_home_profile_shares_the_one_script_no_dead_copy() {
    let project = synced_project();
    project
        .exuno()
        .args(["profile", "add", "hub", "--tools", "claude"])
        .assert()
        .success();
    project.exuno().args(["sync", "--force"]).assert().success();
    // The profile's settings reference ${CLAUDE_PROJECT_DIR}/.claude/hooks/…,
    // so the script has to stay there rather than be copied per config home.
    assert!(project.join(GUARD).is_file());
    assert!(
        !project
            .join(".claude-hub/hooks/agentsync-guard.sh")
            .exists()
    );
    assert!(
        project
            .read(".claude-hub/settings.json")
            .contains(".claude/hooks/agentsync-guard.sh")
    );
}

#[test]
fn guard_the_shared_script_is_not_swept_into_the_profiles_ignore_list() {
    let project = synced_project();
    project
        .exuno()
        .args(["profile", "add", "hub", "--tools", "claude"])
        .assert()
        .success();
    project.exuno().args(["sync", "--force"]).assert().success();
    // Committed outputs: profile homes are personal and ignored, the guard is not.
    assert!(project.read(".gitignore").contains("claude-hub"));
    assert!(!is_git_ignored(&project, GUARD));
}

#[test]
fn guard_a_profile_only_sync_still_writes_the_script() {
    let project = synced_project();
    project
        .exuno()
        .args(["profile", "add", "hub", "--tools", "claude"])
        .assert()
        .success();
    std::fs::remove_dir_all(project.join(".claude/hooks")).unwrap();
    project
        .exuno()
        .args(["sync", "--profile", "hub", "--force"])
        .assert()
        .success();
    assert!(project.join(GUARD).is_file());
}

#[test]
fn guard_a_project_override_replaces_the_shipped_script() {
    let project = synced_project();
    project.write(".ai/src/tools/claude/guard.sh", "#!/bin/sh\nexit 0\n");
    project.exuno().args(["sync", "--force"]).assert().success();
    let path = path_str(&project.join("CLAUDE.md"));
    let output = guard_for(&project, &path);
    assert_eq!(output.status.code(), Some(0));
}
