//! `tests/release.bats`: `exuno release` — bumps VERSION, Cargo.toml, and
//! Cargo.lock together, commits, tags, and (unless `--no-push`) pushes. Every
//! case runs against its own temp checkout; nothing here touches the real
//! repository or pushes anywhere but a throwaway bare remote.

mod common;

use std::path::Path;
use std::process::Command as StdCommand;

use common::Project;
use predicates::prelude::*;

/// The version `release <bump>` writes from the seed's VERSION.
fn seed_version() -> &'static str {
    include_str!("../VERSION").trim()
}

fn bumped(bump: &str) -> String {
    let parts: Vec<u64> = seed_version()
        .split('.')
        .map(|p| p.parse().unwrap())
        .collect();
    let (major, minor, patch) = (parts[0], parts[1], parts[2]);
    match bump {
        "major" => format!("{}.0.0", major + 1),
        "minor" => format!("{major}.{}.0", minor + 1),
        "patch" => format!("{major}.{minor}.{}", patch + 1),
        other => panic!("unknown bump: {other}"),
    }
}

/// A minimal checkout `release` accepts: VERSION, Cargo.toml, Cargo.lock, and
/// a CHANGELOG with a patch section, committed on `main`.
fn checkout() -> Project {
    let project = Project::empty();
    project.git(&["symbolic-ref", "HEAD", "refs/heads/main"]);
    let version = seed_version();
    project.write("VERSION", &format!("{version}\n"));
    project.write(
        "Cargo.toml",
        &format!(
            "[package]\nname = \"exuno\"\nversion = \"{version}\"\nedition = \"2024\"\n\n[dependencies]\nclap = {{ version = \"4.6\", features = [\"derive\"] }}\n"
        ),
    );
    project.write(
        "Cargo.lock",
        &format!(
            "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"exuno\"\nversion = \"{version}\"\ndependencies = [\n \"clap\",\n]\n\n[[package]]\nname = \"clap\"\nversion = \"4.6.0\"\n"
        ),
    );
    project.write(
        "CHANGELOG.md",
        &format!(
            "# Changelog\n\n## {}\n\nA patch.\n\n- one fix\n\n## {version}\n\nThe seed.\n",
            bumped("patch")
        ),
    );
    project.git(&["add", "-A"]);
    project.git(&["commit", "-m", "seed", "--quiet"]);
    project
}

fn absent_git_config() -> std::path::PathBuf {
    std::env::temp_dir().join("agentsync-tests-absent-gitconfig")
}

/// `git <args>` in an arbitrary directory (the bare remote), isolated from
/// the developer's global config the same way `common::Project::git` is.
fn git_in(dir: &Path, args: &[&str]) -> String {
    let output = StdCommand::new("git")
        .args(args)
        .current_dir(dir)
        .env("GIT_CONFIG_GLOBAL", absent_git_config())
        .env("GIT_CONFIG_SYSTEM", absent_git_config())
        .output()
        .unwrap();
    assert!(output.status.success(), "git {args:?} failed in {dir:?}");
    String::from_utf8(output.stdout).unwrap()
}

#[test]
fn release_patch_bumps_version() {
    let project = checkout();
    project
        .exuno()
        .args(["release", "patch", "--no-push"])
        .write_stdin("y\n")
        .assert()
        .success();
    assert_eq!(project.read("VERSION"), format!("{}\n", bumped("patch")));
}

#[test]
fn release_minor_bumps_version() {
    let project = checkout();
    project
        .exuno()
        .args(["release", "minor", "--no-push"])
        .write_stdin("y\n")
        .assert()
        .success();
    assert_eq!(project.read("VERSION"), format!("{}\n", bumped("minor")));
}

#[test]
fn release_major_bumps_version() {
    let project = checkout();
    project
        .exuno()
        .args(["release", "major", "--no-push"])
        .write_stdin("y\n")
        .assert()
        .success();
    assert_eq!(project.read("VERSION"), format!("{}\n", bumped("major")));
}

#[test]
fn release_bumps_cargo_toml_and_cargo_lock_with_version() {
    let project = checkout();
    project
        .exuno()
        .args(["release", "minor", "--no-push"])
        .write_stdin("y\n")
        .assert()
        .success();
    let new_version = bumped("minor");
    let toml = project.read("Cargo.toml");
    assert_eq!(
        toml.lines().filter(|l| l.starts_with("version = ")).count(),
        1
    );
    assert!(toml.contains(&format!("version = \"{new_version}\"")));
    assert!(toml.contains("clap = { version = \"4.6\""));
    let lock = project.read("Cargo.lock");
    assert!(lock.contains(&format!("name = \"exuno\"\nversion = \"{new_version}\"")));
    assert!(lock.contains("version = 4\n"));
    assert!(lock.contains("version = \"4.6.0\""));
}

#[test]
fn release_creates_git_tag() {
    let project = checkout();
    project
        .exuno()
        .args(["release", "patch", "--no-push"])
        .write_stdin("y\n")
        .assert()
        .success();
    let tags = git_in(project.path(), &["tag", "-l"]);
    assert!(tags.lines().any(|t| t == bumped("patch")));
}

#[test]
fn release_tags_with_the_changelog_section_of_the_new_version() {
    let project = checkout();
    project
        .exuno()
        .args(["release", "patch", "--no-push"])
        .write_stdin("y\n")
        .assert()
        .success();
    let message = git_in(
        project.path(),
        &["tag", "-l", "--format=%(contents)", &bumped("patch")],
    );
    assert_eq!(
        message.trim_end_matches('\n'),
        format!("v{}\n\nA patch.\n\n- one fix", bumped("patch"))
    );
}

#[test]
fn release_creates_commit() {
    let project = checkout();
    project
        .exuno()
        .args(["release", "patch", "--no-push"])
        .write_stdin("y\n")
        .assert()
        .success();
    let subject = git_in(project.path(), &["log", "--format=%s", "-1"]);
    assert_eq!(subject.trim_end(), format!("release: v{}", bumped("patch")));
}

#[test]
fn release_commits_version_cargo_toml_and_cargo_lock_together() {
    let project = checkout();
    project
        .exuno()
        .args(["release", "patch", "--no-push"])
        .write_stdin("y\n")
        .assert()
        .success();
    let names = git_in(
        project.path(),
        &["show", "--format=", "--name-only", "HEAD"],
    );
    let mut files: Vec<&str> = names.lines().collect();
    files.sort_unstable();
    assert_eq!(files, ["Cargo.lock", "Cargo.toml", "VERSION"]);
    assert_eq!(git_in(project.path(), &["status", "--porcelain"]), "");
}

#[test]
fn release_default_is_patch() {
    let project = checkout();
    project
        .exuno()
        .args(["release", "--no-push"])
        .write_stdin("y\n")
        .assert()
        .success();
    assert_eq!(project.read("VERSION"), format!("{}\n", bumped("patch")));
}

#[test]
fn release_fails_on_dirty_working_tree() {
    let project = checkout();
    project.write("dirty_file.txt", "uncommitted\n");
    project
        .exuno()
        .args(["release", "patch", "--no-push"])
        .write_stdin("y\n")
        .assert()
        .code(1)
        .stderr(predicate::str::contains("not clean"));
}

#[test]
fn release_fails_with_unknown_bump_type() {
    let project = checkout();
    project
        .exuno()
        .args(["release", "banana"])
        .write_stdin("y\n")
        .assert()
        .code(1)
        .stderr(predicate::str::contains("Unknown bump type"));
}

#[test]
fn release_fails_when_cargo_lock_has_no_agentsync_entry_and_writes_nothing() {
    let project = checkout();
    project.write("Cargo.lock", "version = 4\n");
    project.git(&["commit", "-qam", "lock without agentsync"]);
    project
        .exuno()
        .args(["release", "patch", "--no-push"])
        .write_stdin("y\n")
        .assert()
        .code(1)
        .stderr(predicate::str::contains(
            "Cannot find the exuno crate version in Cargo.lock",
        ))
        .stdout(predicate::str::contains("Continue?").not());
    assert_eq!(project.read("VERSION"), format!("{}\n", seed_version()));
    assert_eq!(git_in(project.path(), &["status", "--porcelain"]), "");
}

#[test]
fn release_fails_without_cargo_toml() {
    let project = checkout();
    project.git(&["rm", "-q", "Cargo.toml"]);
    project.git(&["commit", "-qm", "no manifest"]);
    project
        .exuno()
        .args(["release", "patch", "--no-push"])
        .write_stdin("y\n")
        .assert()
        .code(1)
        .stderr(predicate::str::contains(
            "Must be run from the Exuno repository.",
        ));
}

#[test]
fn release_can_be_cancelled() {
    let project = checkout();
    project
        .exuno()
        .args(["release", "patch", "--no-push"])
        .write_stdin("n\n")
        .assert()
        .success();
    assert_eq!(project.read("VERSION"), format!("{}\n", seed_version()));
}

#[test]
fn release_exits_1_at_end_of_input_on_the_prompt() {
    let project = checkout();
    project
        .exuno()
        .args(["release", "patch", "--no-push"])
        .write_stdin("")
        .assert()
        .code(1)
        .stdout(predicate::str::ends_with("Continue? [Y/n]: "));
    assert_eq!(project.read("VERSION"), format!("{}\n", seed_version()));
}

#[test]
fn release_no_push_does_not_push() {
    let project = checkout();
    project
        .exuno()
        .args(["release", "patch", "--no-push"])
        .write_stdin("y\n")
        .assert()
        .success()
        .stdout(predicate::str::contains("local only"))
        .stdout(predicate::str::contains("--no-push"));
}

#[test]
fn release_pushes_main_and_the_tag_to_origin() {
    let project = checkout();
    let remote_dir = tempfile::tempdir().unwrap();
    let remote = remote_dir.path();
    git_in(remote, &["init", "--bare", "--quiet"]);
    project.git(&["remote", "add", "origin", remote.to_str().unwrap()]);
    project
        .exuno()
        .args(["release", "patch"])
        .write_stdin("y\n")
        .assert()
        .success()
        .stdout(predicate::str::contains("Pushing to origin..."))
        .stdout(predicate::str::contains(format!(
            "Released v{}!",
            bumped("patch")
        )));
    let subject = git_in(remote, &["log", "--format=%s", "-1", "main"]);
    assert_eq!(subject.trim_end(), format!("release: v{}", bumped("patch")));
    let tags = git_in(remote, &["tag", "-l"]);
    assert!(tags.lines().any(|t| t == bumped("patch")));
}

#[test]
fn release_without_an_origin_stops_at_the_push_with_gits_status() {
    let project = checkout();
    project
        .exuno()
        .args(["release", "patch"])
        .write_stdin("y\n")
        .assert()
        .code(128)
        .stdout(predicate::str::contains("Pushing to origin..."))
        .stdout(predicate::str::contains("Released").not());
    let tags = git_in(project.path(), &["tag", "-l"]);
    assert!(tags.lines().any(|t| t == bumped("patch")));
}
